version: '3.8'

services:
#  db:
#    container_name: db
#    image: mongo
#    env_file:
#      - .env
#    restart: always
#    ports:
#      - "27017:27017"
#    volumes:
#      - db_data:/data/db
#      - db_config:/data/configdb
#
#  db-express:
#    container_name: db-express
#    image: mongo-express
#    depends_on:
#      - db
#    ports:
#      - "8081:8081"
#    restart: always
#    env_file:
#      - .env

  puntify-api:
    environment:
      - DOCKER=true
    container_name: api
    build: .
    image: acrpuntify.azurecr.io/puntify-api
    ports:
      - "443:443"
#    links:
#      - db
#    depends_on:
#      - db
    restart: always
  puntify-front:
    environment:
      - DOCKER=true
      - VITE_API_URL=https://localhost:443
    container_name: front
    build: ./frontend/
    image: acrpuntify.azurecr.io/puntify-front

    ports:
      - "80:80"
    restart: always

volumes:
  db_data:
  db_config:
