version: '3.8'

services:
  db:
    container_name: db
    image: mongo
    env_file:
      - .env
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
    networks:
      - bridge

  db-express:
    container_name: db-express
    image: mongo-express
    depends_on:
      - db
    ports:
      - "8081:8081"
    restart: always
    env_file:
      - .env

  puntify-api:
    environment:
      - DOCKER=true
      - MONGO_URL=mongodb://db:27017/
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - algorithm=HS256
      - access_token_expire_minutes=1440
    container_name: api
    build: .
    image: acrpuntify.azurecr.io/puntify-api
    networks:
      - bridge
    ports:
      - "443:443"
    links:
      - db
    depends_on:
      - db
    restart: always
  puntify-front:
    environment:
      - DOCKER=true
      - VITE_API_URL=http://api:443
    container_name: front
    build: ./frontend/
    image: acrpuntify.azurecr.io/puntify-front
    networks:
      - bridge
    ports:
      - "80:80"
    restart: always

volumes:
  db_data:
  db_config:


networks:
  bridge:
    driver: bridge
